PortfolioSite/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PortfolioSite.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            return View();
        }

        public ActionResult Contact()
        {
            return View();
        }
        
    }
}

PortfolioSite/Controllers/SkillController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PortfolioSite.Controllers
{
    public class SkillController : Controller
    {
        // GET: Skill Index
        public ActionResult Index()
        {
            return View();
        }
        // GET: Skill Resume
        public ActionResult Resume()
        {
            return View();
        }
        public ActionResult Work()
        {
            return View();
        }
    }
    
}

PortfolioSite/Views/Home/About.cshtml
@{
    ViewBag.Title = "About me";
}
<body style="background-color:powderblue;">
    <div class="container">
        <div class="text-center">
            <h1 style="font-family: 'Lato', sans-serif; font-size:75px; color:dodgerblue;">About Me</h1>
            <a href="http://dagobah.net/flash/rickroll.swf" style="cursor:default;" target="_blank"><img src="~/Content/ColtonProfile.jpg" class="img-rounded" /></a>
</div> 
        <br />
        <div class="container text-center">
            <p style="font-family:'Roboto Slab',serif; left:auto; font-size:large;">I have always wanted to create. At a young age I found it through music and it stuck with me all my life and now I can say I play over nine instruments. My father being in network administration, taught me how to build computers and I quickly was taking apart electronics to see how they worked I even remember getting in trouble for taking apart my brand new playstation and mounting it into my sister's old easy bake oven. At the start of high school however, I felt a bit lost. Here I was making music and playing with electronics and it was great but I realized I wanted to create things for people to enjoy. It was then I found my next challenge of building sets for plays in the theater department. I caught on very quickly and by my sophomore year I was the Master Builder. I was designing full two story sets, teaching something I loved and making friends with people who cared about the same things I did. After high school I took some time off and even in my time of relaxation I became engaged with playing video games competitively. I spent hours upon hours competing against people from around the world in a popular online video game. In only a few short months I had ranked in the top 10 players in the world.</p>       
        </div>
            
    </div>
</body>

PortfolioSite/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}

PortfolioSite/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
   <body style="background-image:url(../../Content/stockvault-mountains138737.jpg)">
    <div class="container text-center">
       <h1 style="font-family: 'Lato', sans-serif; font-size:100px; color:navy;">Colton Miller</h1>
       <h2 style ="font-family: 'Lato', sans-serif; font-size:75px; color: dodgerblue;">Full Stack Developer</h2>
       <br />
       <br />
       <div class="container" style="align-content:center">
           <div class="col-md-4 row">
               <a href="https://github.com/ColtonMiller" target="_blank">
                   <img src="~/Content/GitHub_Logo.png" style="height:66px;" />
               </a>
           </div>
           <div class="col-md-5 row">
               <a href="https://www.linkedin.com/in/coltonjmmiller" target="_blank">
                   <img src="~/Content/Logo-2C-66px-TM.png" style="height:55px;">
               </a>
           </div>
           <div class="col-md-4 row">
               <a href="https://github.com/ColtonMiller/UglyMuttEntertainmentSite" target="_blank">
                   <img src="~/Content/UME.png" style="height:75px;">
               </a>
           </div>
       </div>
   </div>
  </body>

PortfolioSite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href='http://fonts.googleapis.com/css?family=Roboto+Slab:300,400' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <link href='http://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
</head>
<body>
    <div id="custom-bootstrap-menu" class="navbar navbar-default navbar-fixed-top " role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-menubuilder">
                    <span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
                </button>
            </div>
            <div class="collapse navbar-collapse navbar-menubuilder">
                <ul class="nav navbar-nav navbar-left" style="font-family: 'Roboto Slab', serif; font-size:x-large;">
                    <li>
                        <a href="@Url.Action("Index","Home")" style="color:navy;">Home</a>
                    </li>
                    <li>
                        <a href="@Url.Action("About","Home")" style="color:navy;">About Me</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index","Skill")" style="color:navy;">Skill Set</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Resume","Skill")" style="color:navy;">Resume</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Work","Skill")" style="color:navy;">Work Examples</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

PortfolioSite/Views/Skill/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<body style="background-color:powderblue;">
    <div class="container text-center">
        <h1 style="font-family: 'Lato', sans-serif; font-size:75px; color:dodgerblue;">Skill Set</h1>
        <div class="container row">
            <div class="container row">
                <img src="~/Content/vslogo2012.png" style="height:120px;" />
                <br />
                <img src="~/Content/HTML5_Logo_512.png" style="height:100px;"/>
                <img src="~/Content/CSS3_logo.png" style="height:105px;"/>
                <img src="~/Content/js3.png" style="height:110px;" />
                <br />
                <br />
                <img src="~/Content/ASPNET_logo.png" style="height:85px;"/>
                <br />
                <br />
                <img src="~/Content/sqlserver2012.png" style="height:85px;" />
                <br />
                <br />
            </div>
        </div>
    </div>
</body>

PortfolioSite/Views/Skill/Resume.cshtml
@{
    ViewBag.Title = "Resume";
}

<body style="background-color:powderblue;">
    <div class="container text-center">
        <h1 style="font-family: 'Lato', sans-serif; font-size:75px; color:dodgerblue;">Resume</h1>
    </div>
    <div class="text-center">
        <a href="~/Content/ColtonMillerResume.pdf" target="_blank">
            <img src="~/Content/ColtonMillerResume.jpg" style="width:60%;" /> 
        </a>
            <br />
            <br />
            <div class="row">
                <a class="btn btn-primary view-pdf" href="~/Content/ColtonMillerResume.pdf" target="_blank">View PDF</a>
            </div>
</div>

</body>

PortfolioSite/Views/Skill/Work.cshtml
@{
    ViewBag.Title = "Work";
}

<body style="background-color:powderblue;">
    <div class="container text-center">
        <h1 style="font-family: 'Lato', sans-serif; font-size:75px; color:dodgerblue;">Works</h1>
    </div> 
    <div class="container text-center">
        <a href="https://github.com/ColtonMiller/CombatSim2.0" target="_blank"><h1 style="font-family: 'Lato', sans-serif; font-size:60px; color:navy;">Fight Anything</h1><p style="font-family:'Roboto Slab',serif; left:auto; font-size:large;">A simple Combat simulator where you have 3 weapons and you can...Fight anything.</p></a>
        <div class="row text-center"><img src="~/Content/FA1.png" style="height:250px;" /><img src="~/Content/FA2.png" style="height:250px;" /><img src="~/Content/FA3.png" style="height:250px;" /><img src="~/Content/FA4.png" style="height:250px;" /></div>  
    </div>
    <div class="container text-center">
        <a href="https://github.com/ColtonMiller/Rememberyourlines" target="_blank"><h1 style="font-family: 'Lato', sans-serif; font-size:60px; color:navy;">Remember Your Lines</h1><p style="font-family:'Roboto Slab',serif; left:auto; font-size:large;">Takes in a .txt file of the entire script of MacBeth user can enter anything and the program shows all lines that contain the input. </p></a>  
    </div>
    <div class="row text-center"><img src="~/Content/RYL1.png" style="height:250px;" /><img src="~/Content/ryl2.png" style="height:250px;" /><img src="~/Content/RYL3.png" style="height:250px;" /></div>  
</body>